### ISSUE TITLE
Clean up and improve performance of `generate_HRD_associated_funcs.rs`

### ISSUE THREAD

**Issue by asishallab** [usadellab/prot-scriber#12]
The module `generate_HRD_associated_funcs.rs` us functional. 

However, there are a few minor issues that should be addressed:

* _all_ functions _must_ have Rust-Doc style code comments. `generateHumanReadableDescription` and `mean` e.g. still do not have them
* in line `let mut word_frequencies_map = frequencies(universe.clone());` the word frequencies are calculated for _all_ words, which is not necessary. Instead calculate the frequencies _only_ for the informative words. 
* After classifying words into "informative" and "not informative" a functional iterator retains only the informative words. Refactor function `word_classification_map` to avoid this _double_ loop over all words. Iterate once and use retain in case the word is informative, or the opposite otherwise.
* Set up your editor to always use `rustfmt` on saving a `rs` file. At least format this module. 
* Check if in all cases maximum efficiency has been applied. Avoid multiple looping as e.g. above in word classification.
* Please answer why the main argument `universe_hrd_words:Vec<&str>` is a vector of scalar `&str` and not a vector of `String`. I believe the parsing of the Blast input tables returns `String` vectors (which might not be optimal, by the way...).

**Comment by asishallab** [comment]
One more:

* Please make sure _every_ function in the module has unit tests.

**Comment by Atemia** [comment]
Yes, you are right. [This](https://www.ameyalokare.com/rust/2017/10/12/rust-str-vs-String.html#fn:1) is why I used that approach. Right now for now, it takes can Vec<String>.
