### ISSUE TITLE
Generate regular expression for parsing UniRef

### ISSUE THREAD

**Issue by asishallab** [usadellab/prot-scriber#30]
UniRef is a protein reference database from UniProtKB. There are two versions UniRef50 and 90.
Redundancy has been removed by exclusions of sequence with a significant similarity.

The format of UniRef Fasta headers is different to those of Swissprot and trEMBL. 

Please provide a file with Rust syntax regular expressions. This file will be used as the `-l, --filter-regexs <filter-regexs>` argument to prot-scriber.

**Comment by coeit** [comment]
closed in https://github.com/usadellab/prot-scriber/commit/01251f7b93e1296db41cddd17755f7db5b59fb95
