### ISSUE TITLE
Consider phrases consisting only of non-informative words "unknown protein" or "unknown family"

### ISSUE THREAD

**Issue by asishallab** [usadellab/prot-scriber#33]
Currently, phrases, i.e. sub-sets of candidate descriptions, that only consist of non-informative words are still scored and might be assigned as the final annotation. This should be changed.

If the set of informative words is empty, classify the protein or sequence family as "unknown".

Hint: 
```rust
pub fn generate_human_readable_description(
    // [...]
    let mut informative_words_universe: Vec<String> = vec![];
    // If that universe is empty, don't do an annotation, i.e. ignore non-informative words as the only phrase constant 
```

**Comment by coeit** [comment]
Closed in #36
