### ISSUE TITLE
Add a command-line option to exclude "unknown protein" or "unknown sequence family" from results

### ISSUE THREAD

**Issue by asishallab** [usadellab/prot-scriber#34]
Currently prot-scriber writes out the above default descriptions for queries (protein or family) that could not be assigned a meaningful annotation (human readable description). 

Add a command-line option to exclude these queries from the result table instead of calling them "unknown".

This is an option particularly useful for the Mercator-integration.

Use `--exclude-not-annotated-queries` and short `-x`

**Comment by coeit** [comment]
Closed in #36
