### ISSUE TITLE
Wrong annotations in prot-scriber

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [usadellab/prot-scriber#40]
I was currently again looking thourgh the mercator annotation file and found some more misspelled prot-scriber annotations, in addition to the previous ones. So far, I have found the following:
| wrong anntoation | right annotation? |
| :----- | :----- |
| domai cotaiig protei | domain containing protein|
| trasferase | transferase |
| zinc finger ran binding | zinc finger rna binding |
| ran binding protein m hoolog | rna binding protein m homolog
| ontaining | containing |

It would be good to correct these errors so that users don't have to go and look for them by themselves.

**Comment by asishallab** [comment]
Run experiments to find query proteins for which prot-scriber generates human readable descriptions (HRDs) that resemble the problematic ones seen in the above issue.

Then look at the Blast Hit descriptions to identify those that were used as source(s) for the HRDs, i.e. those that prot-scriber parsed and processed to generate the final HRD.

Look at the regular expressions with capture-replace mechanisms (called `CAPTURE_REPLACE_DESCRIPTION_PAIRS` in default.rs and try to identify which might be the cause for the problematic HRDs.

You can write Unit Tests to reproduce the problematic case.

**Comment by derRiesenOtter** [comment]
### Unterschiedliche Ergebnisse Ubuntu und MacOS

Ubuntu:
Annotee-Identifier      Human-Readable-Description
Soltu.DM.S001650.1      germin member
Soltu.DM.04G035790.1    phosphatidylinositol phosphatidylcholine transfer sfh
Soltu.DM.01G022510.1    5 amp activated kinase subunit gamma
Soltu.DM.01G045390.1    hva
Soltu.DM.07G016620.1    gdsl esterase lipase
Soltu.DM.02G020600.1    arath strubbelig receptor family
Soltu.DM.10G003150.1    sh and domain containing
Soltu.DM.03G026010.1    arm repeat interacting with
Soltu.DM.03G011280.1    increased dna methylation
Soltu.DM.09G022410.3    unknown protein
Soltu.DM.02G015700.1    lrr receptor serine threonine kinase
