### ISSUE TITLE
Optimisation of generated HRDs

### ISSUE THREAD

**Issue by derRiesenOtter** [usadellab/prot-scriber#46]
The assignment of HRDs for following sequences showed room to improve: 

>mercator4v5.0: dihydopyrimidine aminohydrolase & prot-scriber: amidohydro rel domain containing protein & swissprot: no annotation & original description: Dihydropyrimidinase (AHRD V3.3 *** A0A1U8EK03_CAPAN)
Solyc05g010420.2.1 ITAG 4,1
mercator4v5.0: S-adenosyl methionine decarboxylase & prot-scriber: s adenoylmethionine decarboxylae proenzyme & swissprot: no annotation & original description: S-adenosylmethionine decarboxylase 2 AND mercator4v5.0: EC_4.1 carbon-carbon lyase & prot-scriber: s adenoylmethionine decarboxylae proenzyme & swissprot: no annotation & original description: S-adenosylmethionine decarboxylase 2
Solyc03g118750.4.1
mercator4v5.0: phospho-base N-methyltransferase & prot-scriber: phosphoethanolamine n methyltrasferase & swissprot: no annotation & original description: phosphoethanolamine N-methyltransferase AND mercator4v5.0: EC_2.1 transferase transferring one-carbon group & prot-scriber: phosphoethanolamine n methyltrasferase & swissprot: no annotation & original description: phosphoethanolamine N-methyltransferase
mercator4v5.0: component *(PsaH) of PS-I complex & prot-scriber: photosystem i reacton center subunt v chloroplastc & swissprot: no annotation & original description: Photosystem I reaction center subunit VI, chloroplastic (AHRD V3.3 *** A0A2G2WLH8_CAPBA)
Solyc09g011520.3.1
ARATH raus
mercator4v5.0: class tau glutathione S-transferase & prot-scriber: arath glutathione s tranferae & swissprot: no annotation & original description: Glutathione S-transferase-like protein (AHRD V3.3 *** A8DUB0_SOLLC)

For now, only proteins with a ``Solyc...g...`` identifier

Reference data can be found here ``/mnt/data/asis/prot-scriber/evaluation/Solanum_lycopersicum_ITAG_4.0``

Before running prot-scriber, the uniprot databanks should be refreshed ``/mnt/data/asis/UniProt``

prot-scriber will be used twice to see the HRDs when using swissprot alone and swissprot and trembl together.

**Comment by derRiesenOtter** [comment]
Solyc05g010420.2.1:
new protscriber  annotation: s adenosylmethionine decarboxylase proenzyme
error leading to missing s seems to be resolved

Solyc03g118750.4.1:
new protscriber annotation: phosphoethanolamine n methyltransferase
error leading to missing n seems to be resolved

Solyc09g011520.3.1:
new protscriber annotation: glutathione s transferase
error leading to the word 'arath' in the annotation and the error leading to the missing s seems to be resolved

prot-scriber (v0.1.5) was used for this testing - there were no differences between the runs with sprot and sprot + trembl

**Comment by asishallab** [comment]
Fixed with regular expressions in latest prot-scriber version (v0.1.5)
